# Generated by Django 6.0.3 on 2026-04-27 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SLObjectURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_url', models.URLField(help_text='The dynamic URL provided by llRequestURL() in Second Life', max_length=500)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this URL is currently reachable')),
            ],
            options={
                'verbose_name': 'SL Object URL',
                'verbose_name_plural': 'SL Object URLs',
                'ordering': ['-registered_at'],
            },
        ),
    ]
