# Generated by Django 6.0.3 on 2026-04-26 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='category',
            field=models.CharField(choices=[('Build', 'In-World Builds'), ('Product', 'Product Showcase'), ('Event', 'Events & Meetups'), ('Art', 'Concept Art')], default='Build', help_text='Category for filtering', max_length=20),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description shown in lightbox view'),
        ),
    ]
