# Generated by Django 6.0.3 on 2026-05-06 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='image_url',
            field=models.URLField(blank=True, default='', help_text='External image URL (used instead of uploaded file)'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image file (optional if image_url is set)', null=True, upload_to='products/'),
        ),
    ]
