# Generated by Django 6.0.3 on 2026-04-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_name', models.CharField(help_text="The user's Second Life username", max_length=100, verbose_name='SL Name')),
                ('topic', models.CharField(choices=[('Commission Work', 'Commission Work'), ('Product Related Issue', 'Product Related Issue'), ('Complaints', 'Complaints'), ('Suggestions', 'Suggestions'), ('Others', 'Others')], max_length=50)),
                ('message', models.TextField()),
                ('otp_code', models.CharField(blank=True, help_text='Temporary OTP code for verification', max_length=6)),
                ('otp_verified', models.BooleanField(default=False)),
                ('otp_created_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, help_text='Set after OTP is verified and message is submitted', null=True)),
                ('is_read', models.BooleanField(default=False, help_text='Whether an admin has read this message')),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
